@startuml
'https://plantuml.com/sequence-diagram

skinparam ParticipantFontStyle bold
skinparam DatabaseFontStyle bold
skinparam CollectionsFontStyle bold
skinparam BackgroundColor White
skinparam TitleFontSize 25
skinparam TitleFontStyle bold
autonumber "<font color=blue><b>"

title Projet IND8123

database "YFinance API" #720E9E
participant Initialiser #White
participant Simulator #White
database "Local data" #SteelBlue
participant Pricer #White

group Initialisation
Initialiser -> Initialiser: Start
activate Initialiser #LightSlateGrey
Initialiser -> Initialiser: Ask user for \nstock ticker symbol
Initialiser -> "YFinance API": Send request
activate "YFinance API" #LightSlateGrey
"YFinance API"-> Initialiser: Download data
deactivate "YFinance API"
Initialiser -> Simulator: Send data\nfor simulation
activate Simulator #LightSlateGrey
deactivate Initialiser
deactivate "YFinance API"
end

group Simulation
Simulator->Simulator: Initialise simulation\nparameters
loop #LightBlue Simulation methods
Simulator->Simulator: Run Monte-Carlo\nsimulations using\ncurrent method
Simulator->"Local data": Store simulated\ntrajectories
activate "Local data"
deactivate Simulator
end
end


group Pricing
loop #LightBlue Simulation methods
"Local data"->Pricer: Load simulated\ntrajectories
activate Pricer #LightSlateGrey
loop #LightGreen Option types
Pricer->Pricer: Price current\noption type
Pricer->"Local data": Store option\nprice
deactivate "Local data"
Pricer->Pricer: Stop
deactivate Pricer
end
end
end

@enduml
